theme = "onedark"

[editor]
true-color = true
rulers = [80]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.whitespace.render]
space = "all"
tab = "all"

[editor.indent-guides]
render = true
